- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-integration-jobs-all
      - puppet-openstack-litmus-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - puppet-nova-tripleo-standalone
    gate:
      jobs:
        - puppet-nova-tripleo-standalone

- job:
    name: puppet-nova-tripleo-standalone
    parent: tripleo-puppet-ci-centos-8-standalone
    description: |
      TripleO standalone Job running Nova specific Tempest tests.
    vars:
      build_container_images: true
      featureset_override:
        run_tempest: false
        tempest_test_whitelist:
          - 'tempest.api.compute'
          - 'tempest.scenario.test_server_basic_ops'
        use_os_tempest: true
