name    'puppetlabs-nova'
version '2.0.0'
source  'https://github.com/stackforge/puppet-nova'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Nova Module'
description 'Puppet module to install and configure the OpenStack Nova compute service'
project_page 'https://launchpad.net/puppet-openstack'

## Add dependencies, if any:
dependency 'puppetlabs/glance', '>= 2.0.0'
dependency 'puppetlabs/keystone', '>= 2.0.0'
dependency 'puppetlabs/cinder', '>= 2.0.0'
dependency 'puppetlabs/mysql', '>= 0.6.1'
dependency 'puppetlabs/rabbitmq', '>= 2.0.2'
dependency 'puppetlabs/stdlib', '>= 2.5.0'
dependency 'duritong/sysctl', '>= 0.0.1'
dependency 'cprice404/inifile', '>= 0.10.3'
dependency 'dprince/qpid', '>= 1.0.0'
